"""Authentication business logic: register, verify, and token revocation.

Services own every database *write* (DOC section 24). Routes in
`app/api/v1/auth.py` stay thin: validate, delegate here, serialise.

Two details worth calling out:

* Login failures are deliberately indistinguishable -- wrong email and wrong
  password both return the same `INVALID_CREDENTIALS` 401, and a miss still
  performs a dummy bcrypt comparison so response timing does not reveal which
  emails exist (DOC section 31, "user enumeration").
* Logout is a real sign-out: the token's `jti` is stored in `revokedTokens`,
  which `app.api.deps.get_current_user` checks on every request.
"""

from __future__ import annotations

import hashlib
import logging
import secrets
from datetime import UTC, datetime, timedelta
from typing import Any

from pymongo import ReturnDocument
from pymongo.asynchronous.database import AsyncDatabase
from pymongo.errors import DuplicateKeyError

from app.core.config import Settings
from app.core.errors import (
    BadRequestError,
    ConflictError,
    ForbiddenError,
    UnauthorizedError,
)
from app.core.security import create_access_token, hash_password, verify_password
from app.models.user import (
    PASSWORD_RESET_TOKENS_COLLECTION,
    REVOKED_TOKENS_COLLECTION,
    USERS_COLLECTION,
)
from app.utils.mongo import to_object_id, utcnow

logger = logging.getLogger(__name__)


class AuthErrorCode:
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    ACCOUNT_PENDING = "ACCOUNT_PENDING"
    ROLE_NOT_SELF_REGISTERABLE = "ROLE_NOT_SELF_REGISTERABLE"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"


# A syntactically valid bcrypt hash of a random value, compared against when the
# email does not exist. Without it, "no such user" returns in ~1ms while
# "wrong password" takes ~250ms, which is a user-enumeration oracle.
_DUMMY_HASH = "$2b$12$m46OkJhUJGGC2TvMfTPrsONB6BwvHftJsggcc1hz5lL/izBM8geV2"


async def register_user(
    db: AsyncDatabase,
    *,
    name: str,
    email: str,
    password: str,
    phone: str | None,
    role: str,
    settings: Settings,
) -> dict[str, Any]:
    """Create a user and return the stored document.

    Raises `ConflictError` if the email is taken, `ForbiddenError` if the role
    may not self-register.
    """
    from app.models.enums import Role  # local import keeps module import order simple

    try:
        role_enum = Role(role)
    except ValueError as exc:
        raise ForbiddenError(
            f"Unknown role '{role}'",
            code=AuthErrorCode.ROLE_NOT_SELF_REGISTERABLE,
        ) from exc

    if not settings.can_self_register(role_enum):
        raise ForbiddenError(
            f"Public registration is not enabled for the '{role_enum}' role",
            code=AuthErrorCode.ROLE_NOT_SELF_REGISTERABLE,
            details={"self_register_roles": sorted(r.value for r in settings.self_register_roles)},
        )

    now = utcnow()
    document: dict[str, Any] = {
        "name": name,
        "email": email,
        "phone": phone,
        "passwordHash": hash_password(password),
        "role": role_enum,
        # New accounts are usable immediately. DOC section 12 mentions admin
        # approval for operator onboarding; when that lands, flip the default
        # here to UserStatus.PENDING for non-driver roles.
        "status": "ACTIVE",
        "facilityIds": [],
        "createdAt": now,
        "updatedAt": now,
        # Stamped at creation so the "token older than passwordChangedAt" check
        # in get_current_user has a baseline from the very first login.
        "passwordChangedAt": now,
    }

    try:
        await db[USERS_COLLECTION].insert_one(document)
    except DuplicateKeyError as exc:
        # The unique index on `email` is the real guard; this also covers a race
        # between two simultaneous registrations.
        raise ConflictError(
            "An account with that email already exists",
            code=AuthErrorCode.EMAIL_ALREADY_REGISTERED,
        ) from exc
    # `insert_one` mutates `document` in place, so `_id` is now a real ObjectId
    # generated by the server. Nothing here needs to invent an id.

    logger.info("Registered user %s with role %s", document["_id"], role_enum.value)
    return document


async def authenticate_user(
    db: AsyncDatabase,
    *,
    email: str,
    password: str,
) -> dict[str, Any]:
    """Verify credentials and return the user document, stamping `lastLoginAt`."""
    user = await db[USERS_COLLECTION].find_one({"email": email})

    if user is None:
        # Equalise timing against the "user exists, wrong password" path.
        verify_password(password, _DUMMY_HASH)
        raise UnauthorizedError(
            "Invalid email or password",
            code=AuthErrorCode.INVALID_CREDENTIALS,
        )

    if not verify_password(password, user.get("passwordHash", "")):
        logger.info("Failed login for %s: bad password", email)
        raise UnauthorizedError(
            "Invalid email or password",
            code=AuthErrorCode.INVALID_CREDENTIALS,
        )

    status = str(user.get("status", "ACTIVE"))
    if status == "SUSPENDED":
        raise ForbiddenError(
            "This account has been suspended. Contact an administrator.",
            code=AuthErrorCode.ACCOUNT_SUSPENDED,
        )
    if status == "PENDING":
        raise ForbiddenError(
            "This account is awaiting administrator approval.",
            code=AuthErrorCode.ACCOUNT_PENDING,
        )

    updated = await db[USERS_COLLECTION].find_one_and_update(
        {"_id": user["_id"]},
        {"$set": {"lastLoginAt": utcnow(), "updatedAt": utcnow()}},
        return_document=ReturnDocument.AFTER,
    )
    return updated or user


async def revoke_token(
    db: AsyncDatabase,
    *,
    jti: str,
    user_id: str,
    expires_at: int,
    reason: str = "logout",
) -> None:
    """Add a token's `jti` to the denylist until its natural expiry."""
    await db[REVOKED_TOKENS_COLLECTION].update_one(
        {"_id": jti},
        {
            "$setOnInsert": {
                "jti": jti,
                # `RevokedTokenDocument.userId` is an ObjectId, and the JWT `sub`
                # is that id as a string. Convert here so future joins against
                # this collection match `users._id` directly.
                "userId": to_object_id(user_id),
                "exp": datetime.fromtimestamp(expires_at, tz=UTC),
                "revokedAt": utcnow(),
                "reason": reason,
            }
        },
        upsert=True,
    )
    logger.info("Revoked token %s for user %s", jti, user_id)


async def is_token_revoked(db: AsyncDatabase, jti: str) -> bool:
    """True when the token id appears on the denylist."""
    return await db[REVOKED_TOKENS_COLLECTION].find_one({"_id": jti}, {"_id": 1}) is not None


def issue_token_for_user(
    user: dict[str, Any],
    settings: Settings,
) -> tuple[str, int]:
    """Mint an access token for a freshly loaded user document."""
    token, expires_at = create_access_token(
        subject=str(user["_id"]),
        role=str(user["role"]),
        settings=settings,
        extra_claims={
            "email": user.get("email"),
            "name": user.get("name"),
            "status": str(user.get("status", "ACTIVE")),
            "facilityIds": list(user.get("facilityIds") or []),
        },
    )
    remaining = int((expires_at - utcnow()).total_seconds())
    return token, max(0, remaining)


# --- Password reset and change (DOC section 7: "password reset"; section 21:
# "forgot/reset password"; section 31: never store plaintext, rate-limit, log)


def hash_reset_token(raw_token: str) -> str:
    """Hash an emailed reset token for storage and lookup.

    Only the hash is persisted, so a dump of `passwordResetTokens` cannot be
    replayed against `/reset-password`. SHA-256 rather than bcrypt on purpose:
    the input is 32 bytes of `secrets` output, so there is nothing to brute
    force, and redemption has to stay a single indexed `_id` lookup.
    """
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


async def _write_password(
    db: AsyncDatabase,
    *,
    user_id: Any,
    new_password: str,
) -> None:
    """Store a new password and stamp `passwordChangedAt`.

    The single place that writes `passwordHash`. Keeping `passwordChangedAt` in
    the same update is what guarantees the two can never drift: every access
    token issued before this instant stops working immediately, which is the
    intended effect of a password change.
    """
    now = utcnow()
    await db[USERS_COLLECTION].update_one(
        {"_id": user_id},
        {
            "$set": {
                "passwordHash": hash_password(new_password),
                "passwordChangedAt": now,
                "updatedAt": now,
            }
        },
    )


async def create_password_reset(
    db: AsyncDatabase,
    *,
    email: str,
    settings: Settings,
    request_ip: str | None = None,
    user_agent: str | None = None,
) -> tuple[Any | None, str | None]:
    """Mint a reset token for `email` if that account exists.

    Returns `(user_id, raw_token)`. Both are `None` when the address is unknown,
    which the caller must report identically to the success case -- returning
    anything else turns this endpoint into a user-enumeration oracle (DOC
    section 31).

    Any token already outstanding for the account is dropped first, so the
    newest link is always the only one that works.
    """
    user = await db[USERS_COLLECTION].find_one({"email": email}, {"_id": 1, "status": 1})
    if user is None:
        return None, None

    user_id = user["_id"]

    # A suspended or unapproved account must not be able to use "forgot
    # password" to mail itself a working reset link.
    if str(user.get("status", "ACTIVE")) != "ACTIVE":
        logger.info("Password reset requested for non-active account %s", user_id)
        return None, None

    await db[PASSWORD_RESET_TOKENS_COLLECTION].delete_many({"userId": user_id})

    raw_token = secrets.token_urlsafe(settings.password_reset_token_bytes)
    now = utcnow()
    await db[PASSWORD_RESET_TOKENS_COLLECTION].insert_one(
        {
            "_id": hash_reset_token(raw_token),
            "userId": user_id,
            "exp": now + timedelta(seconds=settings.password_reset_expire_seconds),
            "createdAt": now,
            "requestIp": request_ip,
            "userAgent": (user_agent or "")[:255] or None,
        }
    )
    logger.info("Issued password reset token for user %s", user_id)
    return user_id, raw_token


async def consume_password_reset(
    db: AsyncDatabase,
    *,
    raw_token: str,
    new_password: str,
) -> Any:
    """Redeem a reset token and set a new password. Returns the user id.

    `find_one_and_delete` does three jobs in one atomic operation: it looks the
    token up by hash, refuses rows whose `exp` has passed, and removes the row
    so the token is single-use even if two requests race. A token that was
    never issued, already redeemed, or expired all produce the same
    `BadRequestError`.
    """
    now = utcnow()
    document = await db[PASSWORD_RESET_TOKENS_COLLECTION].find_one_and_delete(
        {"_id": hash_reset_token(raw_token), "exp": {"$gt": now}}
    )
    if document is None:
        raise BadRequestError(
            "This password reset link is invalid or has expired. Please request a new one.",
            code=AuthErrorCode.INVALID_RESET_TOKEN,
        )

    user_id = document["userId"]
    await _write_password(db, user_id=user_id, new_password=new_password)

    # Drop any sibling tokens so an older email in the inbox cannot be reused.
    await db[PASSWORD_RESET_TOKENS_COLLECTION].delete_many({"userId": user_id})

    logger.info("Password reset completed for user %s", user_id)
    return user_id


async def change_password(
    db: AsyncDatabase,
    *,
    user_id: Any,
    current_password: str,
    new_password: str,
) -> None:
    """Change the password of an authenticated user.

    The current password is required: an access token proves the session is
    authenticated, not proof that whoever holds it should be able to rotate the
    credential.

    A wrong current password raises `BadRequestError` (400), deliberately *not*
    `UnauthorizedError` (401). The token is perfectly valid - the caller simply
    mistyped - and the client treats any 401 as "this session is dead" and drops
    the user to the login screen. Returning 400 keeps a failed attempt from
    looking like an expired session.
    """
    # `user_id` arrives as the JWT subject, which is a *string*; `users._id` is
    # an ObjectId. Querying with the raw string matches nothing, which would
    # look identical to a deleted account.
    object_id = to_object_id(user_id)
    if object_id is None:
        raise BadRequestError(
            "This account no longer exists",
            code=AuthErrorCode.INVALID_CREDENTIALS,
        )

    user = await db[USERS_COLLECTION].find_one({"_id": object_id}, {"passwordHash": 1})
    if user is None:
        # Unreachable over HTTP: `get_current_user` already rejects a token whose
        # account has gone. Kept so a direct service call cannot write a
        # password onto a missing row.
        raise BadRequestError(
            "This account no longer exists",
            code=AuthErrorCode.INVALID_CREDENTIALS,
        )

    if not verify_password(current_password, user.get("passwordHash", "")):
        logger.info("Rejected password change for %s: wrong current password", user_id)
        raise BadRequestError(
            "Current password is incorrect",
            code=AuthErrorCode.CURRENT_PASSWORD_INCORRECT,
        )

    await _write_password(db, user_id=object_id, new_password=new_password)
    logger.info("Password changed for user %s", user_id)
