"""Authentication business logic: register, verify, and token revocation.

Services own every database *write* (DOC section 24). Routes in
`app/api/v1/auth.py` stay thin: validate, delegate here, serialise.

Two details worth calling out:

* Login failures are deliberately indistinguishable -- wrong email and wrong
  password both return the same `INVALID_CREDENTIALS` 401, and a miss still
  performs a dummy bcrypt comparison so response timing does not reveal which
  emails exist (DOC section 31, "user enumeration").
* Logout is a real sign-out: the token's `jti` is stored in `revokedTokens`,
  which `app.api.deps.get_current_user` checks on every request.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

from pymongo import ReturnDocument
from pymongo.asynchronous.database import AsyncDatabase
from pymongo.errors import DuplicateKeyError

from app.core.config import Settings
from app.core.errors import ConflictError, ForbiddenError, UnauthorizedError
from app.core.security import create_access_token, hash_password, verify_password
from app.models.user import (
    REVOKED_TOKENS_COLLECTION,
    USERS_COLLECTION,
)
from app.utils.mongo import utcnow

logger = logging.getLogger(__name__)


class AuthErrorCode:
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    ACCOUNT_PENDING = "ACCOUNT_PENDING"
    ROLE_NOT_SELF_REGISTERABLE = "ROLE_NOT_SELF_REGISTERABLE"
    TOKEN_REVOKED = "TOKEN_REVOKED"


# A syntactically valid bcrypt hash of a random value, compared against when the
# email does not exist. Without it, "no such user" returns in ~1ms while
# "wrong password" takes ~250ms, which is a user-enumeration oracle.
_DUMMY_HASH = "$2b$12$m46OkJhUJGGC2TvMfTPrsONB6BwvHftJsggcc1hz5lL/izBM8geV2"


async def register_user(
    db: AsyncDatabase,
    *,
    name: str,
    email: str,
    password: str,
    phone: str | None,
    role: str,
    settings: Settings,
) -> dict[str, Any]:
    """Create a user and return the stored document.

    Raises `ConflictError` if the email is taken, `ForbiddenError` if the role
    may not self-register.
    """
    from app.models.enums import Role  # local import keeps module import order simple

    try:
        role_enum = Role(role)
    except ValueError as exc:
        raise ForbiddenError(
            f"Unknown role '{role}'",
            code=AuthErrorCode.ROLE_NOT_SELF_REGISTERABLE,
        ) from exc

    if not settings.can_self_register(role_enum):
        raise ForbiddenError(
            f"Public registration is not enabled for the '{role_enum}' role",
            code=AuthErrorCode.ROLE_NOT_SELF_REGISTERABLE,
            details={"self_register_roles": sorted(r.value for r in settings.self_register_roles)},
        )

    now = utcnow()
    document: dict[str, Any] = {
        "name": name,
        "email": email,
        "phone": phone,
        "passwordHash": hash_password(password),
        "role": role_enum,
        # New accounts are usable immediately. DOC section 12 mentions admin
        # approval for operator onboarding; when that lands, flip the default
        # here to UserStatus.PENDING for non-driver roles.
        "status": "ACTIVE",
        "facilityIds": [],
        "createdAt": now,
        "updatedAt": now,
    }

    try:
        await db[USERS_COLLECTION].insert_one(document)
    except DuplicateKeyError as exc:
        # The unique index on `email` is the real guard; this also covers a race
        # between two simultaneous registrations.
        raise ConflictError(
            "An account with that email already exists",
            code=AuthErrorCode.EMAIL_ALREADY_REGISTERED,
        ) from exc
    # `insert_one` mutates `document` in place, so `_id` is now a real ObjectId
    # generated by the server. Nothing here needs to invent an id.

    logger.info("Registered user %s with role %s", document["_id"], role_enum.value)
    return document


async def authenticate_user(
    db: AsyncDatabase,
    *,
    email: str,
    password: str,
) -> dict[str, Any]:
    """Verify credentials and return the user document, stamping `lastLoginAt`."""
    user = await db[USERS_COLLECTION].find_one({"email": email})

    if user is None:
        # Equalise timing against the "user exists, wrong password" path.
        verify_password(password, _DUMMY_HASH)
        raise UnauthorizedError(
            "Invalid email or password",
            code=AuthErrorCode.INVALID_CREDENTIALS,
        )

    if not verify_password(password, user.get("passwordHash", "")):
        logger.info("Failed login for %s: bad password", email)
        raise UnauthorizedError(
            "Invalid email or password",
            code=AuthErrorCode.INVALID_CREDENTIALS,
        )

    status = str(user.get("status", "ACTIVE"))
    if status == "SUSPENDED":
        raise ForbiddenError(
            "This account has been suspended. Contact an administrator.",
            code=AuthErrorCode.ACCOUNT_SUSPENDED,
        )
    if status == "PENDING":
        raise ForbiddenError(
            "This account is awaiting administrator approval.",
            code=AuthErrorCode.ACCOUNT_PENDING,
        )

    updated = await db[USERS_COLLECTION].find_one_and_update(
        {"_id": user["_id"]},
        {"$set": {"lastLoginAt": utcnow(), "updatedAt": utcnow()}},
        return_document=ReturnDocument.AFTER,
    )
    return updated or user


async def revoke_token(
    db: AsyncDatabase,
    *,
    jti: str,
    user_id: str,
    expires_at: int,
    reason: str = "logout",
) -> None:
    """Add a token's `jti` to the denylist until its natural expiry."""
    await db[REVOKED_TOKENS_COLLECTION].update_one(
        {"_id": jti},
        {
            "$setOnInsert": {
                "jti": jti,
                "userId": user_id,
                "exp": datetime.fromtimestamp(expires_at, tz=UTC),
                "revokedAt": utcnow(),
                "reason": reason,
            }
        },
        upsert=True,
    )
    logger.info("Revoked token %s for user %s", jti, user_id)


async def is_token_revoked(db: AsyncDatabase, jti: str) -> bool:
    """True when the token id appears on the denylist."""
    return await db[REVOKED_TOKENS_COLLECTION].find_one({"_id": jti}, {"_id": 1}) is not None


def issue_token_for_user(
    user: dict[str, Any],
    settings: Settings,
) -> tuple[str, int]:
    """Mint an access token for a freshly loaded user document."""
    token, expires_at = create_access_token(
        subject=str(user["_id"]),
        role=str(user["role"]),
        settings=settings,
        extra_claims={
            "email": user.get("email"),
            "name": user.get("name"),
            "status": str(user.get("status", "ACTIVE")),
            "facilityIds": list(user.get("facilityIds") or []),
        },
    )
    remaining = int((expires_at - utcnow()).total_seconds())
    return token, max(0, remaining)
